openapi: 3.2.0
info:
  description: API for Synadia Control Plane / Synadia Cloud
  title: Synadia Control Plane / Synadia Cloud Team Service Account…
  version: beta
servers:
- description: Path to Synadia Control Plane Server Api
  url: '{baseUrl}/api'
  variables:
    baseUrl:
      default: ''
security:
- bearerAuth: []
  sessionAuth: []
tags:
- name: team-service-account
paths:
  /core/beta/service-accounts/team/{serviceAccountId}:
    delete:
      operationId: deleteTeamServiceAccount
      parameters:
      - explode: false
        in: path
        name: serviceAccountId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Delete Team Service Account
      tags:
      - team-service-account
      x-doc-tags:
      - Team Service Accounts
    get:
      operationId: getTeamServiceAccount
      parameters:
      - explode: false
        in: path
        name: serviceAccountId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccountViewResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Get Team Service Account
      tags:
      - team-service-account
      x-doc-tags:
      - Team Service Accounts
    patch:
      operationId: updateTeamServiceAccount
      parameters:
      - explode: false
        in: path
        name: serviceAccountId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceAccountUpdateRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceAccountViewResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Update Team Service Account
      tags:
      - team-service-account
      x-doc-tags:
      - Team Service Accounts
  /core/beta/service-accounts/team/{serviceAccountId}/tokens:
    get:
      operationId: listTeamServiceAccountTokens
      parameters:
      - explode: false
        in: path
        name: serviceAccountId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppUserAccessTokenListResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: List Access Tokens for Team Service Account
      tags:
      - team-service-account
      x-doc-tags:
      - Team Service Accounts
    post:
      operationId: createTeamServiceAccountToken
      parameters:
      - explode: false
        in: path
        name: serviceAccountId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppUserAccessTokenCreateRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppUserAccessTokenCreateResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Create Acess Token for Team Service Account
      tags:
      - team-service-account
      x-doc-tags:
      - Team Service Accounts
components:
  schemas:
    NatsUserInfo:
      example:
        user_public_key: user_public_key
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        user_public_key:
          type: string
      required:
      - id
      - name
      - user_public_key
      type: object
    SystemState:
      enum:
      - Provisioning
      - Connected
      - Disconnected
      type: string
    SystemInfo:
      example:
        jetstream_enabled: true
        http_gateway_url: http_gateway_url
        is_tenant: true
        connection_type: null
        managed_by: null
        config_mode: true
        server_urls: server_urls
        user_jwt_expires_in_secs: 7
        jetstream_tiers:
        - jetstream_tiers
        - jetstream_tiers
        name: name
        id: id
        state: null
        jetstream_domain: jetstream_domain
      properties:
        config_mode:
          type: boolean
        connection_type:
          $ref: '#/components/schemas/SystemConnectionType'
        http_gateway_url:
          type: string
        id:
          type: string
        is_tenant:
          type: boolean
        jetstream_domain:
          type: string
        jetstream_enabled:
          type: boolean
        jetstream_tiers:
          items:
            type: string
          type: array
        managed_by:
          $ref: '#/components/schemas/SystemManagedBy'
        name:
          type: string
        server_urls:
          type: string
        state:
          $ref: '#/components/schemas/SystemState'
        user_jwt_expires_in_secs:
          format: int64
          type: integer
      required:
      - config_mode
      - connection_type
      - id
      - is_tenant
      - jetstream_enabled
      - name
      - state
      - user_jwt_expires_in_secs
      type: object
    AppUserAssignRequest:
      example:
        role_id: role_id
      properties:
        role_id:
          type: string
      required:
      - role_id
      type: object
    AppUserAssignResponse:
      example:
        role_name: role_name
        nats_user:
          user_public_key: user_public_key
          name: name
          id: id
        system:
          jetstream_enabled: true
          http_gateway_url: http_gateway_url
          is_tenant: true
          connection_type: null
          managed_by: null
          config_mode: true
          server_urls: server_urls
          user_jwt_expires_in_secs: 7
          jetstream_tiers:
          - jetstream_tiers
          - jetstream_tiers
          name: name
          id: id
          state: null
          jetstream_domain: jetstream_domain
        app_user:
          identifier: identifier
          name: name
          id: id
          type: null
        role_id: role_id
        created: 2000-01-23 04:56:07+00:00
        scope: null
        team_app_user:
          role_name: role_name
          role_id: role_id
          pending_invitation: true
          id: id
        resource_id: resource_id
        team:
          name: name
          id: id
        account:
          user_jwt: user_jwt
          auth_type: null
          user_cred: user_cred
          account_public_key: account_public_key
          name: name
          user_jwt_expires_in_secs: 0
          id: id
          is_platform_account: true
          is_scp_account: true
          is_system_account: true
      properties:
        account:
          $ref: '#/components/schemas/AccountInfo'
        app_user:
          $ref: '#/components/schemas/AppUserInfo'
        created:
          format: date-time
          type: string
        nats_user:
          $ref: '#/components/schemas/NatsUserInfo'
        resource_id:
          type: string
        role_id:
          type: string
        role_name:
          type: string
        scope:
          $ref: '#/components/schemas/AppRoleScope'
        system:
          $ref: '#/components/schemas/SystemInfo'
        team:
          $ref: '#/components/schemas/TeamInfo'
        team_app_user:
          $ref: '#/components/schemas/TeamAppUserInfo'
      required:
      - app_user
      - created
      - resource_id
      - role_id
      - role_name
      - scope
      - team_app_user
      type: object
    AppUserAccessTokenCreateResponse:
      allOf:
      - $ref: '#/components/schemas/AppUserAccessTokenViewResponse'
      - required:
        - token
      example:
        token: token
      properties:
        token:
          type: string
      type: object
    AccountAuthType:
      enum:
      - jwt
      - tls
      - nkey
      - username
      type: string
    ServiceAccountViewResponse:
      example:
        role_id: role_id
        created: 2000-01-23 04:56:07+00:00
        scope: null
        name: name
        resources:
          key:
            role_name: role_name
            nats_user:
              user_public_key: user_public_key
              name: name
              id: id
            system:
              jetstream_enabled: true
              http_gateway_url: http_gateway_url
              is_tenant: true
              connection_type: null
              managed_by: null
              config_mode: true
              server_urls: server_urls
              user_jwt_expires_in_secs: 7
              jetstream_tiers:
              - jetstream_tiers
              - jetstream_tiers
              name: name
              id: id
              state: null
              jetstream_domain: jetstream_domain
            app_user:
              identifier: identifier
              name: name
              id: id
              type: null
            role_id: role_id
            created: 2000-01-23 04:56:07+00:00
            scope: null
            team_app_user:
              role_name: role_name
              role_id: role_id
              pending_invitation: true
              id: id
            resource_id: resource_id
            team:
              name: name
              id: id
            account:
              user_jwt: user_jwt
              auth_type: null
              user_cred: user_cred
              account_public_key: account_public_key
              name: name
              user_jwt_expires_in_secs: 0
              id: id
              is_platform_account: true
              is_scp_account: true
              is_system_account: true
        id: id
        last_active: last_active
        team_id: team_id
      properties:
        created:
          format: date-time
          type: string
        id:
          type: string
        last_active:
          type:
          - string
          - 'null'
        name:
          type: string
        resources:
          additionalProperties:
            $ref: '#/components/schemas/AppUserAssignResponse'
          description: resource keys must be in format ServiceAccountResourceScope:resource_id
          type: object
        role_id:
          type: string
        scope:
          $ref: '#/components/schemas/ServiceAccountScope'
        team_id:
          type: string
      required:
      - created
      - id
      - last_active
      - name
      - resources
      - role_id
      - scope
      type: object
    AppUserAccessTokenListResponse:
      example:
        items:
        - expires: expires
          created: 2000-01-23 04:56:07+00:00
          name: name
          id: id
          last_active: last_active
        - expires: expires
          created: 2000-01-23 04:56:07+00:00
          name: name
          id: id
          last_active: last_active
      properties:
        items:
          items:
            $ref: '#/components/schemas/AppUserAccessTokenViewResponse'
          type: array
      required:
      - items
      type: object
    ServiceAccountScope:
      enum:
      - App
      - Team
      type: string
    AppUserAccessTokenCreateRequest:
      example:
        expires: 2000-01-23 04:56:07+00:00
        never_expires: true
        name: name
      properties:
        expires:
          format: date-time
          type: string
        name:
          type: string
        never_expires:
          type: boolean
      required:
      - name
      type: object
    ServiceAccountUpdateRequest:
      example:
        role_id: role_id
        name: name
        resources:
          key: null
      properties:
        name:
          type: string
        resources:
          additionalProperties:
            $ref: '#/components/schemas/ServiceAccountUpdateRequest_resources_value'
          description: 'Resource keys must be in format ServiceAccountResourceScope:resource_id.

            To delete a resource, set its key to null'
          type: object
        role_id:
          type: string
      type: object
    AppUserInfo:
      example:
        identifier: identifier
        name: name
        id: id
        type: null
      properties:
        id:
          type: string
        identifier:
          type: string
        name:
          type: string
        type:
          $ref: '#/components/schemas/AppUserType'
      required:
      - id
      - name
      - type
      type: object
    AppUserAccessTokenViewResponse:
      example:
        expires: expires
        created: 2000-01-23 04:56:07+00:00
        name: name
        id: id
        last_active: last_active
      properties:
        created:
          format: date-time
          type: string
        expires:
          type:
          - string
          - 'null'
        id:
          type: string
        last_active:
          type:
          - string
          - 'null'
        name:
          type: string
      required:
      - created
      - id
      - name
      type: object
    AppUserType:
      enum:
      - Person
      - AppServiceAccount
      - TeamServiceAccount
      type: string
    TeamInfo:
      example:
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
      required:
      - id
      - name
      type: object
    AppRoleScope:
      enum:
      - App
      - Team
      - System
      - Account
      - NatsUser
      type: string
    AccountInfo:
      example:
        user_jwt: user_jwt
        auth_type: null
        user_cred: user_cred
        account_public_key: account_public_key
        name: name
        user_jwt_expires_in_secs: 0
        id: id
        is_platform_account: true
        is_scp_account: true
        is_system_account: true
      properties:
        account_public_key:
          type: string
        auth_type:
          $ref: '#/components/schemas/AccountAuthType'
        id:
          type: string
        is_platform_account:
          type: boolean
        is_scp_account:
          type: boolean
        is_system_account:
          type: boolean
        name:
          type: string
        user_cred:
          type: string
        user_jwt:
          type: string
        user_jwt_expires_in_secs:
          format: int64
          type: integer
      required:
      - auth_type
      - id
      - is_platform_account
      - is_scp_account
      - is_system_account
      - name
      - user_jwt_expires_in_secs
      type: object
    ServiceAccountUpdateRequest_resources_value:
      allOf:
      - $ref: '#/components/schemas/AppUserAssignRequest'
      type:
      - object
      - 'null'
    SystemManagedBy:
      enum:
      - byon
      - sdkube
      type: string
    TeamAppUserInfo:
      example:
        role_name: role_name
        role_id: role_id
        pending_invitation: true
        id: id
      properties:
        id:
          type: string
        pending_invitation:
          type: boolean
        role_id:
          type: string
        role_name:
          type: string
      required:
      - id
      - pending_invitation
      - role_id
      - role_name
      type: object
    SystemConnectionType:
      default: Agent
      enum:
      - Agent
      - Direct
      type: string
  securitySchemes:
    bearerAuth:
      bearerFormat: Personal Access Token
      scheme: bearer
      type: http
    sessionAuth:
      in: cookie
      name: control_plane_session
      type: apiKey
