openapi: 3.2.0
info:
  description: API for Synadia Control Plane / Synadia Cloud
  title: Synadia Control Plane / Synadia Cloud Alert API
  version: beta
servers:
- description: Path to Synadia Control Plane Server Api
  url: '{baseUrl}/api'
  variables:
    baseUrl:
      default: ''
security:
- bearerAuth: []
  sessionAuth: []
tags:
- name: Alert
paths:
  /core/beta/alerts/{alertId}:
    get:
      operationId: getAlert
      parameters:
      - explode: false
        in: path
        name: alertId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertViewResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Get Alert
      tags:
      - Alert
      x-doc-tags:
      - Alerts
  /core/beta/alerts/{alertId}/acknowledge:
    patch:
      operationId: acknowledgeAlert
      parameters:
      - explode: false
        in: path
        name: alertId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Acknowledge Alert
      tags:
      - Alert
      x-doc-tags:
      - Alerts
components:
  schemas:
    AccountAuthType:
      enum:
      - jwt
      - tls
      - nkey
      - username
      type: string
    PromSampleValue:
      example:
        value: 1.4658129805029452
        timestamp: 6
      properties:
        timestamp:
          format: int64
          type: integer
        value:
          format: double
          type: number
      required:
      - timestamp
      - value
      type: object
    SystemState:
      enum:
      - Provisioning
      - Connected
      - Disconnected
      type: string
    AlertRuleSeverity:
      enum:
      - Info
      - Warn
      - Error
      - Critical
      type: string
    AlertRuleType:
      enum:
      - SystemDefault
      - System
      - AccountDefault
      - Account
      - Stream
      - Consumer
      type: string
    SystemInfo:
      example:
        jetstream_enabled: true
        http_gateway_url: http_gateway_url
        is_tenant: true
        connection_type: null
        managed_by: null
        config_mode: true
        server_urls: server_urls
        user_jwt_expires_in_secs: 7
        jetstream_tiers:
        - jetstream_tiers
        - jetstream_tiers
        name: name
        id: id
        state: null
        jetstream_domain: jetstream_domain
      properties:
        config_mode:
          type: boolean
        connection_type:
          $ref: '#/components/schemas/SystemConnectionType'
        http_gateway_url:
          type: string
        id:
          type: string
        is_tenant:
          type: boolean
        jetstream_domain:
          type: string
        jetstream_enabled:
          type: boolean
        jetstream_tiers:
          items:
            type: string
          type: array
        managed_by:
          $ref: '#/components/schemas/SystemManagedBy'
        name:
          type: string
        server_urls:
          type: string
        state:
          $ref: '#/components/schemas/SystemState'
        user_jwt_expires_in_secs:
          format: int64
          type: integer
      required:
      - config_mode
      - connection_type
      - id
      - is_tenant
      - jetstream_enabled
      - name
      - state
      - user_jwt_expires_in_secs
      type: object
    AccountInfo:
      example:
        user_jwt: user_jwt
        auth_type: null
        user_cred: user_cred
        account_public_key: account_public_key
        name: name
        user_jwt_expires_in_secs: 0
        id: id
        is_platform_account: true
        is_scp_account: true
        is_system_account: true
      properties:
        account_public_key:
          type: string
        auth_type:
          $ref: '#/components/schemas/AccountAuthType'
        id:
          type: string
        is_platform_account:
          type: boolean
        is_scp_account:
          type: boolean
        is_system_account:
          type: boolean
        name:
          type: string
        user_cred:
          type: string
        user_jwt:
          type: string
        user_jwt_expires_in_secs:
          format: int64
          type: integer
      required:
      - auth_type
      - id
      - is_platform_account
      - is_scp_account
      - is_system_account
      - name
      - user_jwt_expires_in_secs
      type: object
    AlertViewResponse:
      example:
        severity: null
        closed_at: 2000-01-23 04:56:07+00:00
        created: 2000-01-23 04:56:07+00:00
        system_id: system_id
        metric_value: 0.8008281904610115
        message: message
        alert_rule:
          severity: null
          created: 2000-01-23 04:56:07+00:00
          system_id: system_id
          duration_in_secs: 0
          message: message
          threshold_expression_metric: threshold_expression_metric
          threshold_fixed_value: 1.4658129805029452
          is_enabled: true
          account_id: account_id
          consumer_name: consumer_name
          rule_type: null
          stream_name: stream_name
          metric: metric
          threshold_operator: threshold_operator
          id: id
          threshold_expression_multiplier: 6.027456183070403
        sample_values:
        - value: 1.4658129805029452
          timestamp: 6
        - value: 1.4658129805029452
          timestamp: 6
        is_acknowledged: true
        account_id: account_id
        consumer_name: consumer_name
        system:
          jetstream_enabled: true
          http_gateway_url: http_gateway_url
          is_tenant: true
          connection_type: null
          managed_by: null
          config_mode: true
          server_urls: server_urls
          user_jwt_expires_in_secs: 7
          jetstream_tiers:
          - jetstream_tiers
          - jetstream_tiers
          name: name
          id: id
          state: null
          jetstream_domain: jetstream_domain
        stream_name: stream_name
        threshold_value: 5.962133916683182
        AcknowledgedByAppUserID: AcknowledgedByAppUserID
        id: id
        is_firing: true
        alert_rule_id: alert_rule_id
        account:
          user_jwt: user_jwt
          auth_type: null
          user_cred: user_cred
          account_public_key: account_public_key
          name: name
          user_jwt_expires_in_secs: 0
          id: id
          is_platform_account: true
          is_scp_account: true
          is_system_account: true
        acknowledged_at: 2000-01-23 04:56:07+00:00
        is_closed: true
      properties:
        AcknowledgedByAppUserID:
          type: string
        account:
          $ref: '#/components/schemas/AccountInfo'
        account_id:
          type: string
        acknowledged_at:
          format: date-time
          type: string
        alert_rule:
          $ref: '#/components/schemas/AlertRuleViewResponse'
        alert_rule_id:
          type: string
        closed_at:
          format: date-time
          type: string
        consumer_name:
          type: string
        created:
          format: date-time
          type: string
        id:
          type: string
        is_acknowledged:
          type: boolean
        is_closed:
          type: boolean
        is_firing:
          type: boolean
        message:
          type: string
        metric_value:
          format: double
          type: number
        sample_values:
          items:
            $ref: '#/components/schemas/PromSampleValue'
          type: array
        severity:
          $ref: '#/components/schemas/AlertRuleSeverity'
        stream_name:
          type: string
        system:
          $ref: '#/components/schemas/SystemInfo'
        system_id:
          type: string
        threshold_value:
          format: double
          type: number
      required:
      - alert_rule
      - alert_rule_id
      - created
      - id
      - is_acknowledged
      - is_closed
      - is_firing
      - message
      - metric_value
      - sample_values
      - severity
      - threshold_value
      type: object
    SystemManagedBy:
      enum:
      - byon
      - sdkube
      type: string
    AlertRuleViewResponse:
      example:
        severity: null
        created: 2000-01-23 04:56:07+00:00
        system_id: system_id
        duration_in_secs: 0
        message: message
        threshold_expression_metric: threshold_expression_metric
        threshold_fixed_value: 1.4658129805029452
        is_enabled: true
        account_id: account_id
        consumer_name: consumer_name
        rule_type: null
        stream_name: stream_name
        metric: metric
        threshold_operator: threshold_operator
        id: id
        threshold_expression_multiplier: 6.027456183070403
      properties:
        account_id:
          type: string
        consumer_name:
          type: string
        created:
          format: date-time
          type: string
        duration_in_secs:
          type: integer
        id:
          type: string
        is_enabled:
          type: boolean
        message:
          type: string
        metric:
          type: string
        rule_type:
          $ref: '#/components/schemas/AlertRuleType'
        severity:
          $ref: '#/components/schemas/AlertRuleSeverity'
        stream_name:
          type: string
        system_id:
          type: string
        threshold_expression_metric:
          type: string
        threshold_expression_multiplier:
          type: number
        threshold_fixed_value:
          type: number
        threshold_operator:
          type: string
      required:
      - created
      - duration_in_secs
      - id
      - is_enabled
      - message
      - metric
      - rule_type
      - severity
      - threshold_operator
      type: object
    SystemConnectionType:
      default: Agent
      enum:
      - Agent
      - Direct
      type: string
  securitySchemes:
    bearerAuth:
      bearerFormat: Personal Access Token
      scheme: bearer
      type: http
    sessionAuth:
      in: cookie
      name: control_plane_session
      type: apiKey
